[2022-11-17T19:51:40.887+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-11-17T19:51:14.316740+00:00 [queued]>
[2022-11-17T19:51:40.915+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-11-17T19:51:14.316740+00:00 [queued]>
[2022-11-17T19:51:40.915+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-17T19:51:40.916+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-11-17T19:51:40.917+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-17T19:51:40.955+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-11-17 19:51:14.316740+00:00
[2022-11-17T19:51:40.970+0000] {standard_task_runner.py:55} INFO - Started process 1521 to run task
[2022-11-17T19:51:40.982+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2022-11-17T19:51:14.316740+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpzk6_bo_5']
[2022-11-17T19:51:40.989+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask download_dataset_task
[2022-11-17T19:51:41.195+0000] {task_command.py:376} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-11-17T19:51:14.316740+00:00 [running]> on host 2f138cf78b7c
[2022-11-17T19:51:41.513+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-17T19:51:14.316740+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-17T19:51:14.316740+00:00
[2022-11-17T19:51:41.520+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-17T19:51:41.521+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSL https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz > /opt/***/yellow_tripdata_2021-01.csv.gz && gunzip /opt/***/yellow_tripdata_2021-01.csv']
[2022-11-17T19:51:41.568+0000] {subprocess.py:86} INFO - Output:
[2022-11-17T19:51:42.238+0000] {subprocess.py:93} INFO - gzip: /opt/***/yellow_tripdata_2021-01.csv: unknown suffix -- ignored
[2022-11-17T19:51:42.238+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-17T19:51:42.270+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-17T19:51:42.292+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20221117T195114, start_date=20221117T195140, end_date=20221117T195142
[2022-11-17T19:51:42.368+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 2.; 1521)
[2022-11-17T19:51:42.435+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-17T19:51:42.578+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
