[2022-11-19T17:38:36.453+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: green_taxi_data_v1.download_dataset_task manual__2022-11-19T17:31:11.536081+00:00 [queued]>
[2022-11-19T17:38:36.475+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: green_taxi_data_v1.download_dataset_task manual__2022-11-19T17:31:11.536081+00:00 [queued]>
[2022-11-19T17:38:36.476+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-19T17:38:36.476+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-19T17:38:36.476+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-19T17:38:36.506+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-11-19 17:31:11.536081+00:00
[2022-11-19T17:38:36.521+0000] {standard_task_runner.py:55} INFO - Started process 58316 to run task
[2022-11-19T17:38:36.540+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'green_taxi_data_v1', 'download_dataset_task', 'manual__2022-11-19T17:31:11.536081+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_homework.py', '--cfg-path', '/tmp/tmpx58z9yf9']
[2022-11-19T17:38:36.550+0000] {standard_task_runner.py:83} INFO - Job 242: Subtask download_dataset_task
[2022-11-19T17:38:36.796+0000] {task_command.py:376} INFO - Running <TaskInstance: green_taxi_data_v1.download_dataset_task manual__2022-11-19T17:31:11.536081+00:00 [running]> on host b8836091f311
[2022-11-19T17:38:36.880+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-19T17:38:36.946+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=green_taxi_data_v1
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-19T17:31:11.536081+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-19T17:31:11.536081+00:00
[2022-11-19T17:38:36.948+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-19T17:38:36.948+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-11.parquet > /opt/***/green_tripdata_2022-11.parquet']
[2022-11-19T17:38:36.973+0000] {subprocess.py:86} INFO - Output:
[2022-11-19T17:38:37.242+0000] {subprocess.py:93} INFO - curl: (22) The requested URL returned error: 403
[2022-11-19T17:38:37.248+0000] {subprocess.py:97} INFO - Command exited with return code 22
[2022-11-19T17:38:37.268+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-19T17:38:37.275+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=green_taxi_data_v1, task_id=download_dataset_task, execution_date=20221119T173111, start_date=20221119T173836, end_date=20221119T173837
[2022-11-19T17:38:37.298+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 242 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 22.; 58316)
[2022-11-19T17:38:37.315+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-19T17:38:37.356+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
