[2022-11-18T20:15:00.635+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget manual__2022-11-18T20:14:59.037705+00:00 [queued]>
[2022-11-18T20:15:00.650+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget manual__2022-11-18T20:14:59.037705+00:00 [queued]>
[2022-11-18T20:15:00.650+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T20:15:00.650+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T20:15:00.650+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T20:15:00.671+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): wget> on 2022-11-18 20:14:59.037705+00:00
[2022-11-18T20:15:00.679+0000] {standard_task_runner.py:55} INFO - Started process 69485 to run task
[2022-11-18T20:15:00.686+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'manual__2022-11-18T20:14:59.037705+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp228ozffp']
[2022-11-18T20:15:00.686+0000] {standard_task_runner.py:83} INFO - Job 73: Subtask wget
[2022-11-18T20:15:00.805+0000] {task_command.py:376} INFO - Running <TaskInstance: LocalIngestionDag.wget manual__2022-11-18T20:14:59.037705+00:00 [running]> on host 2f138cf78b7c
[2022-11-18T20:15:00.917+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T20:14:59.037705+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T20:14:59.037705+00:00
[2022-11-18T20:15:00.919+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-18T20:15:00.920+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSL https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz > OUTPUT_FILE_TEMPLATE && gunzip -f OUTPUT_FILE_TEMPLATE']
[2022-11-18T20:15:00.936+0000] {subprocess.py:86} INFO - Output:
[2022-11-18T20:15:03.369+0000] {subprocess.py:93} INFO - gzip: OUTPUT_FILE_TEMPLATE: unknown suffix -- ignored
[2022-11-18T20:15:03.370+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-18T20:15:03.392+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-18T20:15:03.398+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=wget, execution_date=20221118T201459, start_date=20221118T201500, end_date=20221118T201503
[2022-11-18T20:15:03.418+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 73 for task wget (Bash command failed. The command returned a non-zero exit code 2.; 69485)
[2022-11-18T20:15:03.466+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T20:15:03.505+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
